---
title: "WordleGuesser"
output: html_document
date: '2022-04-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import word list
```{r}
#Import word list
#words <- read.table("words2.txt")
words <- data.frame(scan("page1.txt", what = "character"))
colnames(words) <- "Word"

words$Word <- tolower(words$Word)
```

Load in required libraries
```{r}
library(dplyr)
library(stringr)
library(shiny)
library(gtools)
```
Data Cleaning
```{r}
#Only 5 letter words
words_df <- words %>% 
  mutate(Length = nchar(Word)) %>%
  filter(Length == 5) %>% 
  select(Word)


#Ensure column is unique

words_df <- words_df %>% 
    group_by(Word) %>%
    tally() %>%
    filter(n == 1) #remove duplicates
```

Main Functions
```{r}
#Returns words with specified letter in specified position
place_holder_letter <- function(let, pos, df) {
  #Case if let = ""
  if (let == "") {
    return(df)
  }
  
  df_mutated <- df %>%
    mutate(let1 = substring(Word, 1, 1)
           , let2 = substring(Word, 2, 2)
           , let3 = substring(Word, 3, 3)
           , let4  = substring(Word, 4, 4)
           , let5 = substring(Word, 5, 5))
  
  if (pos == 1) {
    guesses <- df_mutated %>% filter(let1 == let)
  } else if (pos == 2) {
    guesses <- df_mutated %>% filter(let2 == let)
  } else if (pos == 3) {
    guesses <- df_mutated %>% filter(let3 == let)
  } else if (pos == 4) {
    guesses <- df_mutated %>% filter(let4 == let)
  } else {
    guesses <- df_mutated %>% filter(let5 == let)
  }
  
  return(guesses %>% select(Word))
}

#Returns words with letter not in specified position
out_of_pos_letter <- function(let, pos, df) {
  #Case if let = ""
  if (let == "") {
    return(df)
  }
  
  df_mutated <- df %>%
    mutate(let1 = substring(Word, 1, 1)
           , let2 = substring(Word, 2, 2)
           , let3 = substring(Word, 3, 3)
           , let4  = substring(Word, 4, 4)
           , let5 = substring(Word, 5, 5))
  
  if (pos == 1) {
    guesses <- df_mutated %>% filter(let1 != let)
  } else if (pos == 2) {
    guesses <- df_mutated %>% filter(let2 != let)
  } else if (pos == 3) {
    guesses <- df_mutated %>% filter(let3 != let)
  } else if (pos == 4) {
    guesses <- df_mutated %>% filter(let4 != let)
  } else {
    guesses <- df_mutated %>% filter(let5 != let)
  }
  
  return(guesses %>% select(Word))
}
  


#Returns words from a dataframe that don't contain a specific letter
#Returns words from a dataframe that contain a specific letter
#Uses goodLet to determine whether to include or exclude letters
good_bad_letters <- function(let = "", goodLet = TRUE, df) {
  if (let == "") {
    result <- df
    
  } else {
    if (goodLet) {
      if (nchar(let) > 1) {
        #find all permutations for pattern
        pat_vec <- pattern_perms(let)
        
        #convert string into form for filter function
        str_pat <- unlist(lapply(toString(pat_vec), gsub, pattern = ", ", replacement = "|"))
      
      } else {
        str_pat <- str_incl_regex(let)
      } 
      
      #filter for words containing a specific letter  
      result <- df %>% filter(str_detect(Word, str_pat))
    } else {
      #filter for words that do not contain a specific letter
      if (nchar(let) > 1){
        result <- df %>% filter(!str_detect(Word, char_or(let)))
      } else {
        result <- df %>% filter(!str_detect(Word, let))
      }
    }
    colnames(result) <- ("Word")
  }
  
  return(result)
}
 

#joins up to three data frames
join_three_df <- function(df1 = NULL, df2 = NULL, df3 = NULL) {
  
  if (is.null(df1) & is.null(df2)) {
    result <- df3
  } else if (is.null(df1) & is.null(df3)) {
    result <- df2
  } else if (is.null(df2) & is.null(df3)) {
    result <- df1
  } else if (is.null(df1)) {
    result <- df2 %>% inner_join(df3, by = "Word")
  } else if (is.null(df2)) {
    result <- df1 %>% inner_join(df3, by = "Word")
  } else if (is.null(df3)) {
    result <- df1 %>% inner_join(df2, by = "Word")
  } else if (is.null(df1) & is.null(df2) & is.null(df3)) {
    result <- words_df
  } else {
    result <-  df1 %>% inner_join(df2, by = "Word") %>% inner_join(df3, by = "Word")
  }
  
  return(result)
}

#joins up to six data frames
join_six_df <- function(df1 = NULL, df2 = NULL, df3 = NULL, df4 = NULL, df5 = NULL, df6 = NULL){
  
  if (is.null(df1) & is.null(df2) & is.null(df3)) {
    
    result <- join_three_df(df4, df5, df6) %>%
    select(Word)
  } else if (is.null(df4) & is.null(df5) & is.null(df6)) {
    result <- join_three_df(df1, df2, df3) %>%
    select(Word)
    
  } else {
     result <- join_three_df(df1, df2, df3) %>%
      inner_join(join_three_df(df4, df5, df6), by = "Word") %>%
    select(Word)
  }
  
  return(result)
  
}

```

Helper functions
```{r}
#inserts regex characters'.*' between characters in a string
str_incl_regex <- function(letters) {
  str <- gsub(", ", "", letters)
  str <- gsub("", ".*", str)
  
  len <- nchar(str)
  
  str <- substring(str, 1, len)
 
  return(str)
}

#inserts an '|' between characters in a string
char_or <- function(letters) {
  
  str <- gsub("", "|", letters)
  
  len <- nchar(str)
  
  str <- substring(str, 2, len - 1)
 
  return(str)
}

#returns vector of permutations given a string of characters
pattern_perms <- function(pattern) {
  len <- nchar(pattern)
  #number of permutations
  num_perm <- factorial(len)
  pat_vec <- unlist(strsplit(pattern, ""))
  #return(pat_vec)
  perms_matrix <- permutations(len, len, pat_vec)
  
  row_vec <- c(toString(perms_matrix[1,]))
  
  for (i in 2:num_perm) {
    #need to collapse each row into strings and c
    #concatenate each string onto a result vector
    row_vec <- c(row_vec, toString(perms_matrix[i,]))
  
  }
  #need to use apply function to apply gsub and char_bracket to all elements of vector
  #to get vector string elements in the right regex pattern
  result <- lapply(row_vec, gsub, pattern = ", ", replacement = "")
  result <- lapply(result, str_incl_regex)
  result <- unlist(result)
  
  return(result) 
}
```

Shiny app
```{r}
textInput3<-function (inputId, label, value = "",...) 
{
    div(style="display:inline-block",
        tags$label(label, `for` = inputId), 
        tags$input(id = inputId, type = "text", value = value,...))
}


ui <- fluidPage(
  shinythemes::themeSelector(),
  titlePanel("Wordle Guessor"),
  textInput(inputId = "good_letters", label = "Included letters:", value = "", width = "15%", placeholder = "Included letters"),
  textInput(inputId = "bad_letters", label = "Excluded letters:", value = "", width = "15%", placeholder = "Excluded letters"),

  
  #textOutput("Input letters by position:"),
  strong("Input letters by position:"),
  splitLayout(
    textInput(inputId = "Letter_1", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_2", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_3", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_4", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_5", label = "", value = "", placeholder = "__"),
    cellWidths = 40
  ),
  strong("Input letters out of position:"),
  splitLayout(
    textInput(inputId = "Letter_6", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_7", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_8", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_9", label = "", value = "", placeholder = "__"),
    textInput(inputId = "Letter_10", label = "", value = "", placeholder = "__"),
    cellWidths = 40
  ),
  
   mainPanel(
      tabsetPanel(
        tabPanel("Possible Words", tableOutput("summary"))
                 
                 #verbatimTextOutput("summary"))
                 
      )
    )
)

server <- function(input, output, session) {
 
  
  final_results <- reactive({
    toString(join_three_df(
      join_six_df(good_bad_letters(input$good_letters, TRUE, words_df)
                  , good_bad_letters(input$bad_letters, FALSE, words_df)
                  , place_holder_Letter(input$Letter_1, 1, words_df)
                  , place_holder_Letter(input$Letter_2, 2, words_df)
                  , place_holder_Letter(input$Letter_3, 3, words_df)
                  , place_holder_Letter(input$Letter_4, 4, words_df)
                  ),
      
      join_six_df(place_holder_Letter(input$Letter_5, 5, words_df)
                  , out_of_pos_letter(input$Letter_6, 1, words_df)
                  , out_of_pos_letter(input$Letter_7, 2, words_df)
                  , out_of_pos_letter(input$Letter_8, 3, words_df)
                  , out_of_pos_letter(input$Letter_9, 4, words_df)
                  , out_of_pos_letter(input$Letter_10, 5, words_df)
                  )
    
      )$Word)
  })
  
  output$summary <- renderTable({final_results()})
  
}

shinyApp(ui, server)
```



